// Code generated by "jade.go"; DO NOT EDIT.

package main

import (
	"bytes"
	"io"

	"github.com/Joker/hpp"
)

const (
	index__0 = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/></head></html>`
)

func Jade_index(buffer *bytes.Buffer) {

	r, w := io.Pipe()
	go func() {
		buffer := &WriterAsBuffer{w}

		buffer.WriteString(index__0)

		w.Close()
	}()
	hpp.Format(r, buffer)
}
